name: superbai
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  geolocator: ^12.0.0 
  permission_handler: ^11.3.1 
  geocoding: ^3.0.0
  cupertino_icons: ^1.0.8
  package_info_plus: ^8.0.0  
  url_launcher: ^6.3.0 
  firebase_core: ^3.15.1
  firebase_auth: ^5.6.2
  intl: ^0.20.2
  cloud_firestore: ^5.6.12
  wear: ^1.1.0  # For communicating with Wear OS watch

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/superbai_text.PNG
    - assets/bottom_illustration.png 
    - assets/image_cae9e2.png 
    - assets/image_cd33ff.png 
    - assets/image_cbc3bb.png
    - assets/dashboard_images/banner.png
    - assets/dashboard_images/cleaning_icon.png
    - assets/dashboard_images/cooking_icon.jpg
    - assets/dashboard_images/laundry_icon.png
    - assets/dashboard_images/elder_care_icon.png
    - assets/dashboard_images/baby_sitter_icon.png
    - assets/dashboard_images/all_rounder_icon.png
    - assets/success_illustration.PNG
    - assets/chat_icon.png
    - assets/close_icon.png
    - assets/whatsapp_icon.png
    - assets/message_icon.png
    - assets/verified_badge.png
    - assets/linking_icon.png